[theme]
base="light"
primaryColor="#e50914"                # Netflix red for buttons/sliders
backgroundColor="#ffffff"             # Main content area white
secondaryBackgroundColor="#000000"    # Sidebar dark black
textColor="#ffffff"                   # Sidebar text white
font="sans serif"