[theme]
base = "light"
primaryColor = "#e50914"
backgroundColor = "#ffffff"             # Main content background: white
secondaryBackgroundColor = "#000000"    # Sidebar background: black
textColor = "#000000"                   # Text in main content: black (THIS is the fix)
font = "sans serif"