[theme]
base="light"
primaryColor="#e50914"               # 🔴 Netflix red (buttons/sliders)
backgroundColor="#ffffff"            # ⚪ White main background
secondaryBackgroundColor="#000000"   # ⚫ Sidebar background
textColor="#000000"                  # ⚫ Main text (black on white)
font="sans serif"