[theme]
base = "light"
primaryColor = "#e50914"                # Netflix red for buttons and sliders
backgroundColor = "#ffffff"             # White background for the main content area
secondaryBackgroundColor = "#000000"    # Sidebar solid black
textColor = "#ffffff"                   # Sidebar white text for visibility
font = "sans serif"